Requirement api
WalterTano/UCU-1-2023-BD-Obligatorio-Backend pull request #41
Opened 2023-06-23 05:00 UTC by santiagodeolivera

2023-06-23 19:10 UTC, jumpert commented on src/controllers/users.controller.ts
> +        console.log("1:", skills);
este console lo necesitas? o lo utilizaste para probar?

2023-06-23 21:41 UTC, WalterTano requested changes

2023-06-23 21:41 UTC, WalterTano commented on src/controllers/requirements.controller.ts
> +        const res = await requirementModel.hasRequirement(necessityId, skillId);
Retorna hasRequierment, lo cual retorna un booleano, en vez del requisito.

2023-06-23 21:41 UTC, WalterTano commented on src/routes/skillEnum.routes.ts
Esta ruta para qué es?

El método para obtener todas las skills del sistema para mostrarlo como opciones debería estar en la entidad de skills, simplemente puede ser GET /skills sin ningún filtro.
Para evitar que esta ruta esté protegida, hay que aplicar el middleware para validar JWT adentro del router para todas las rutas menos esa en específico (o sea, para el POST, PUT y otros GETs, excepto para el que permite obtener todas las habilidades).

2023-06-23 21:42 UTC, santiagodeolivera commented on src/controllers/requirements.controller.ts
> +        const res = await requirementModel.hasRequirement(necessityId, skillId);
Porque el requisito solo es una asociación entre una necesidad y una habilidad. No hay más información en el requisito

2023-06-23 21:43 UTC, WalterTano commented on src/controllers/requirements.controller.ts
> +        const res = await requirementModel.hasRequirement(necessityId, skillId);
De igual forma, retornar un booleano no coincide con el proposito del endpoint. Debería retornar una instancia única de la entidad.
Si no tiene sentido, se puede eliminar el endpoint directamente.

2023-06-23 21:45 UTC, santiagodeolivera commented on src/controllers/requirements.controller.ts
> +        const res = await requirementModel.hasRequirement(necessityId, skillId);
¿Entonces cómo se determina si una necesidad tiene como requerimiento cierta habilidad?

2023-06-23 21:46 UTC, WalterTano commented on src/controllers/requirements.controller.ts
> +        const res = await requirementModel.hasRequirement(necessityId, skillId);
Este endpoint no hace eso, retorna una fila única de la entidad que asocia a la habilidad con el requisito. Si esto no aporta valor o no tiene sentido, el endpoint puede no existir.
Para conseguir esa funcionalidad, el consumidor del endpoint puede usar el dato retornado para verificarlo, o notar que al no recibir ningún dato, entonces no existe la asociación.

2023-06-23 22:35 UTC, santiagodeolivera commented on src/routes/skillEnum.routes.ts
El GET /skills representa las habilidades que poseen los usuarios

2023-06-23 22:37 UTC, santiagodeolivera commented on src/controllers/requirements.controller.ts
> +        const res = await requirementModel.hasRequirement(necessityId, skillId);
No entiendo. El requerimiento es una representación de la tabla "necesidad_req_habilidad", la cual solo tiene dos campos:
id_necesidad y nombre_habilidad. Así que cuando se pide la información del requerimiento de una necesidad concreta a una habilidad concreta, no hay información que devolver, más allá de si dicho requerimiento existe o no

2023-06-23 22:53 UTC, WalterTano commented on src/controllers/requirements.controller.ts
> +        const res = await requirementModel.hasRequirement(necessityId, skillId);
Si te parece que no tiene sentido el endpoint, entonces no debería existir.

De lo contrario, podés incluir esos 2 campos y si en el futuro se fuera a agregar un campo a esa relación, se puede añadir y devolver en la respuesta.

2023-06-23 22:53 UTC, WalterTano commented on src/routes/skillEnum.routes.ts
Oka, entonces está bien este endpoint

2023-06-24 02:13 UTC, WalterTano approved these changes

2023-06-24 02:13 UTC, merged